# Generated by Django 2.2.14 on 2020-07-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('name', models.CharField(max_length=49)),
                ('lname', models.CharField(max_length=49)),
                ('id', models.IntegerField(help_text='Preparation time in minutes', primary_key=True, serialize=False)),
            ],
        ),
    ]
