# Generated by Django 2.2.14 on 2020-07-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ifsc', models.CharField(max_length=11)),
                ('bank_id', models.IntegerField()),
                ('branch', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='bank',
            name='lname',
        ),
        migrations.AlterField(
            model_name='bank',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
