# Generated by Django 2.2.14 on 2020-07-05 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_data', '0003_auto_20200705_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='bank_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_data.Bank'),
        ),
    ]
